### ISSUE TITLE
Integrate LDAP?

### ISSUE THREAD

**Issue by emmatyping** [ocf/devpi#1]
devpi has support for LDAP integration https://github.com/devpi/devpi-ldap

Maybe we should use it?

**Comment by dkess** [comment]
How often do we expect staffers to actually interact with this service? Isn't it mostly managed by automatic operations?

**Comment by emmatyping** [comment]
Yeah I am pretty sure it isn't worth the complexity. I just am not sure if people would be interested in the private registry feature or not. If not then it doesn't really matter and we can ignore this.

**Comment by emmatyping** [comment]
I don't think we will need this. If that changes we can always add it later.
